application:
  port: 8000
  host: 0.0.0.0
  jwt_signing_key: "DO_NOT_USE"
database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "hermod"
  require_ssl: false
twilio:
  account_sid: "ACb10051bdd7ea0a98dfdb32ab7077a461"
  auth_token: "2aa3cced7cc1ccd27c756b1914fc2bfa"
  base_url: "https://api.twilio.com/2010-04-01/"
  from: "+15078892204"
postmark:
  server_auth_token: "DO_NOT_USE"
  base_url: "https://api.postmarkapp.com/"
  from: "DO_NOT_USE"
