application:
  host: 0.0.0.0
  base_url: "http://hermod-lk26w.ondigitalocean.app"
  honeycomb_url: "https://collector:4317"
database:
  require_ssl: true
email_client:
  base_url: "https://api.postmarkapp.com"
